### PR TITLE
Daffy qt joystick

### PR DESCRIPTION
**Pull request by afdaniele**

### CODE REVIEW

**Comment by afdaniele** [comment]
@light5551 I tested this PR but I don't see any GUI showing up. I'm running it with `dts devel run -X -L joystick`. Any suggestion on how to get it to work? I can start from bash inside the container with `dts devel run -X --cmd bash` and then do `rqt_image_view` and see the GUI correctly but the joystick does not show up.

**Comment by light5551** [comment]
@afdaniele I tested in a slightly different way. Like:
1. `dts devel run -X --cmd bash`
2. `cd packages/virtual_joystick/scripts/`
3.  `python3 virtual_joystick_gui.py duckie`

I have added a commit (#19). Now `dts devel run -X -L joystick` will work

**Comment by afdaniele** [comment]
Great, it works now!
One last thing, how hard is it to make the window smaller?
I'm attaching screenshots of the old and new GUI, we should try to get down to the old size.

New:
keyboard_gui_new

Old:
keyboard_gui_old

**Comment by light5551** [comment]
Done. #20

**Comment by afdaniele** [comment]
@light5551 
I tested this, the size now looks great!
I am having two issues though.

- If I press `E` to activate the emergency stop, the red symbol shows up but then when I press again it does not go away. I can then drive, it is just that the symbol does not go away and the arrows do not light up anymore after the first time I press `E`.

- I can control my duckiebot with the arrows even when the windows is not in focus. This is an issue for two reasons. 1. We cannot have two or more windows controlling different robots, they would all drive. 2. It is dangerous, I almost drove a Duckiebot off my desk while I was typing in another window.

Can you please take a look?
Thanks

**Comment by light5551** [comment]
done #22

**Comment by light5551** [comment]
Hi. I understand that aido is in progress right now, but could you tell when will you have a time for the next review?

**Comment by afdaniele** [comment]
hey guys, I'm using it right now with the Autolab control center for AIDO, will keep you posted.

**Comment by afdaniele** [comment]
image

**Comment by light5551** [comment]
Thx for reviews. fixed error #23

**Comment by ripl-internal** [comment]
@light5551 is it possible to add an icon to the application?
image

**Comment by afdaniele** [comment]
I have this issue.
If I press the button with the mouse, the messages are smooth (there is no jump in the values), if I use the keyboard instead, I see that the value jumps between `0.47752` and `0`.
See video attached.


https://user-images.githubusercontent.com/22665009/102925547-33657f80-4459-11eb-8e79-2bc72da049ed.mp4

**Comment by afdaniele** [comment]
@light5551 ^

**Comment by light5551** [comment]
#26 fixed and  add icon of application.

**Comment by afdaniele** [comment]
@light5551 
FYI, I've made a few changes: 
- fixed a bug with events being captured even though the window was not in focus;
- updated the logo;
- implemented a proper shutdown sequence;
- increased the frequency;
Commit: https://github.com/duckietown/dt-gui-tools/commit/575c1b519ae44c0696bad72ff3de85de59f7e2c1

**Pull request merged**
